# Generated by Django 3.0.5 on 2020-04-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.CharField(max_length=300)),
                ('enseignant', models.CharField(max_length=300)),
                ('duree', models.CharField(max_length=30)),
                ('ects', models.CharField(max_length=30)),
                ('prerequis', models.CharField(max_length=30)),
                ('objectif', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('evaluation', models.CharField(max_length=200)),
            ],
        ),
    ]
