# Generated by Django 3.0.5 on 2020-04-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emploidutemps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomducours', models.CharField(max_length=100)),
                ('enseignant', models.CharField(max_length=100)),
                ('horaire', models.DateTimeField()),
                ('salle', models.CharField(max_length=80)),
            ],
        ),
    ]
